"""Update user model

Revision ID: 0f629eacd367
Revises: e561761c0b2a
Create Date: 2023-12-12 15:04:40.698288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f629eacd367'
down_revision: Union[str, None] = 'e561761c0b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Moderator')
    op.add_column('Administrator', sa.Column('email', sa.String(), nullable=False))
    op.add_column('DefaultUser', sa.Column('email', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DefaultUser', 'email')
    op.drop_column('Administrator', 'email')
    op.create_table('Moderator',
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Moderator_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Moderator_pkey')
    )
    # ### end Alembic commands ###
