"""Delete password column

Revision ID: 27ce56b19cf6
Revises: 6aebb24d420a
Create Date: 2023-12-13 00:24:23.893404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ce56b19cf6'
down_revision: Union[str, None] = '6aebb24d420a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Administrator', 'password')
    op.drop_column('DefaultUser', 'password')
    op.drop_column('Moderator', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Moderator', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('DefaultUser', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Administrator', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
