"""update file model

Revision ID: 7eada458b6db
Revises: 078d6e620c9e
Create Date: 2023-12-22 02:02:36.686629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7eada458b6db'
down_revision: Union[str, None] = '078d6e620c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('File', 'body',
               existing_type=postgresql.BYTEA(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('File', 'body',
               existing_type=postgresql.BYTEA(),
               nullable=False)
    # ### end Alembic commands ###
