"""Update user model for auth

Revision ID: ae11f50ef8db
Revises: 0f629eacd367
Create Date: 2023-12-12 23:43:04.208784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae11f50ef8db'
down_revision: Union[str, None] = '0f629eacd367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Moderator',
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Administrator')
    op.add_column('DefaultUser', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('DefaultUser', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('DefaultUser', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('DefaultUser', sa.Column('hashed_password', sa.String(length=1024), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('DefaultUser', 'hashed_password')
    op.drop_column('DefaultUser', 'is_verified')
    op.drop_column('DefaultUser', 'is_superuser')
    op.drop_column('DefaultUser', 'is_active')
    op.create_table('Administrator',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Administrator_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Administrator_pkey')
    )
    op.drop_table('Moderator')
    # ### end Alembic commands ###
