"""Update user models

Revision ID: e561761c0b2a
Revises: 026a579f5ceb
Create Date: 2023-12-08 18:09:23.484294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e561761c0b2a'
down_revision: Union[str, None] = '026a579f5ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Administrator', sa.Column('password', sa.String(), nullable=False))
    op.add_column('DefaultUser', sa.Column('password', sa.String(), nullable=False))
    op.add_column('Moderator', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Moderator', 'password')
    op.drop_column('DefaultUser', 'password')
    op.drop_column('Administrator', 'password')
    # ### end Alembic commands ###
