"""Add new abstract model: objectFileDirectory

Revision ID: f9e8f320ed7d
Revises: bf1b00daabd4
Create Date: 2023-12-05 18:11:19.409545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e8f320ed7d'
down_revision: Union[str, None] = 'bf1b00daabd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('File', sa.Column('path', sa.String(), nullable=False))
    op.drop_column('Folder', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Folder', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('File', 'path')
    # ### end Alembic commands ###
